# Generated by Django 4.2.1 on 2023-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_publicacion_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='upload',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
